baseURL = "https://your-site.github.io/"
title = "What Just Happened NOW"
languageCode = "en-us"

enableRobotsTXT = true

[params]
  description = "What Just Happened NOW, The Latest From Science, Tech and The World Around Us"
  mainSections = ["post"]
  
  [sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
