# -------------------------------
# Social Icons (Facebook + X)
# -------------------------------
[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://facebook.com/wjhnow"          # ← Change this
[social.params]
icon = "brand-facebook"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com/wjhnow"             # ← Change this
[social.params]
icon = "brand-x"

[[social]]
identifier = "Twitter"
name = "Twitter"
url = "https://t.me/wjh_now"             # ← Change this
[social.params]
icon = "brand-Twitter"
